version: "3.2"
services:
  bot:
    restart: always
    image: mcr.microsoft.com/playwright:focal
    command: ["node", "./index.js"]
    working_dir: /usr/app/dist
    volumes:
      - ./dist:/usr/app/dist
      - ./logs:/usr/app/dist/logs
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    restart: always
    image: redis:alpine
    volumes:
      - redis-data:/data

  localtunnel:
    image: efrecon/localtunnel
    restart: always
    links:
      - bot
    ports:
      - 8888:8080
    command:
      --local-host bot --port 8080 --subdomain angelmariages

volumes:
  redis-data:
