version: "3.2"
services:
  bot:
    restart: always
    image: arm32v7/node:lts-alpine
    command: ["node", "./index.js"]
    working_dir: /usr/app/dist
    volumes:
      - ./dist:/usr/app/dist
      - ./logs:/usr/app/dist/logs
    ports:
      - 8888:8080
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    restart: always
    image: arm32v7/redis
    volumes:
      - redis-data:/data

volumes:
  redis-data:
