version: '3.2'
services:
  bot:
    restart: always
    image: mcr.microsoft.com/playwright:focal
    command: ["node" , "./index.js"]
    working_dir: /usr/app/dist
    volumes:
      - ./dist:/usr/app/dist
      - ./logs:/usr/app/logs
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - 8888:8080

  redis:
    restart: always
    image: redis:alpine
